cyberark/conjur-openapi-spec

conjur-openapi.yml

Fixes issue with python client not returning any value from http requests.
Changed the return schema for some HTTP functions from `application/json: {}` to
```json
application/json:
schema:
type: object
```
This is a temporary fix. Eventually these functions will need actual return schemas specified. However currently there are no return object schemas specified in the standard so this will unblock the testing PR #39. A new issue has been opened to address the return schema issue #43.

Updated return schema for openapi definitions

---

Jenkinsfile

Allows for viewing of all automated processes on Jenkins not just integration tests
Added a linting stage to the Jenkins CI pipeline
Partially Addresses #20 The pipeline still needs to be split into cleaner stages with better feedback. Just wanted to get linting included in Jenkins CI, will fully address this issue in a second PR.

Added linting stage to Jenkinsfile

---

.github/workflows/linting.yml
Jenkinsfile
bin/lint_spec
bin/lint_tests
conjur-openapi.yml
test/python/test_api.py

Will help keep the yaml cleaner and eliminate any accidental errors from bad formatting in the file. A YAML linting step will have to be added to both Jenkins and Github Actions after the file meets the linting standards.
Added a check in the lint_tests file which will lint the OpenAPI YAML specification

Added yaml linting for openapi spec file

---

.github/workflows/main.yml
.github/workflows/rebase.yml

Makes sure that all PR's have been rebased on main before being pulled into the main branch
Added a GitHub action for checking to make sure that a PR branch has been rebased on master. This
is similar to the action used on the main [Conjur repo](https://github.com/cyberark/conjur/blob/master/.github/workflows/main.yml)
Resolves: #55

Added check for rebasing into main workflow

---

.gitignore
Jenkinsfile
bin/integration_tests

Increases segmentation on pipeline runs and makes understanding failures easier
Increased the level of segmentation overall for the pipeline. This should help keep test runs separate once we start adding integration tests for the other clients.
Resolves #20

Updated pipeline stages for Jenkinsfile

---

.github/workflows/api_contract.yml
CONTRIBUTING.md
Jenkinsfile
bin/api_test
conjur-openapi.yml
docker-compose.yml
test/Dockerfile.api

This PR sets up Schemathesis tests to the OpenAPI project.
Schemathesis generates and executes test cases for each 
Conjur OSS endpoint, ensuring that the server and the OpenAPI 
spec are compliant. 
By default, tests are run on every endpoint in the spec, however 
a target endpoint can be specified to reduce scope.
This makes it easy to test new endpoints - add the endpoint, 
run the API test.
The test run is containerized, and included in the current 
`docker-compose` environment.
Resolves #33
For each endpooint, Schemathesis generates tests like so:
- The first test case fills variable data with hard-coded example data provided by the OpenAPI spec.
- The rest of the test cases are filled with random data that meets spec formatting requirements.  
These do a good job of stress testing …

Add API Contract Testing

---

test/python/api_config.py
test/python/test_authn_api.py

Made tests reload the default policy on exit so tests don't interfere with eachother
Resolves #82

Made tests reload the default policy for conjur on exit

---

bin/start_editor

Makes editing easier, means you do not need to import the file each time you restart the editor
Changed launch variables for swagger editor container to make the spec file open by default
Resolves #96

Made swagger editor launch with spec file open by default

---

CHANGELOG.md
spec/secrets.yml
test/config/policy.yaml
test/config/webservice.yml
test/python/api_config.py
test/python/test_policies_api.py
test/python/test_resources_api.py
test/python/test_secrets_api.py
test/python/test_status_api.py

Added `expires` keyword to secrets endpoint. Also added expanded integration tests for secrets endpoint
Resolves #64 #102
NOTE: All calls with the expirations query parameter are required to also specify an empty body (in the generated python client). This is due to an issue on the [openapi generated](https://github.com/OpenAPITools/openapi-generator/issues/8300) client which I am currently working on fixing.

Secrets expiry endpoint

---

CHANGELOG.md
spec/openapi.yml
spec/roles.yml
test/python/api_config.py
test/python/test_roles_api.py

This PR is intended to update the API spec for Roles endpoints by including definitions and tests
for POST and DELETE requests to `/roles/{account}/{kind}/{identifier}?members&member="{role}"`.
Adds query parameters `all` and `memberships` to Roles spec, and tests each.
DONE:
- `GET /roles/{account}/{kind}/{identifier}`
- adds query parameters and possible status responses 
- adds testing for each status response
- `POST /roles/{account}/{kind}/{identifier}?members&member="{role}"`
- describes the request in the API spec
- adds tests for each possible status response
- `DELETE /roles/{account}/{kind}/{identifier}?members&member="{role}"`
- describes the request in the API spec
- adds tests for each possible status response
Resolves #65 
Resolves #67 
Resolves #68

Update Roles API Spec

---

spec/policies.yml
test/python/test_policies_api.py

Added integration tests for all response codes in policies API. I left out the 409 response because I was unable to evoke it with consistency so that other tests were not affected. May circle back to it, however I don't think it is that important to include it.
Resolves #101

Expanded tests for policies endpoints

---

spec/resources.yml
spec/roles.yml
test/python/test_resources_api.py
test/python/test_roles_api.py

- _What's changed? Why were these changes made?_
On Roles and Resources endpoints, the behavior of Conjur when given
multiple optional query parameters is unclear. This commit tests
their relationships and defines it in the API spec.
Resolves #114

Tests and documents API responses when given multiple optional params

---

CHANGELOG.md
spec/authentication.yaml
spec/openapi.yml
test/python/test_authn_api.py

Added GCP authenticate endpoint to spec file. In place of standing up an external GCP authenticator I have made a unit test to confirm that the client makes an appropriate call to the server.
Resolves #61

Added GCP authenticate endpoint to spec file

---

test/python/test_roles_api.py

Cannot use `assertEqual` on arrays as it checks for indexed equality (elements at each index are the same). What we really wanted was to check that each element was in the array.
Fixes test which would fail occasionally. 
Resolves #133

Fixed python integration test array equality check

---

CHANGELOG.md
spec/authentication.yaml
spec/openapi.yml

This PR adds the `/authn-k8s/:service-id/inject-client-cert` endpoint to the OpenAPI spec. This
PR includes material blocking spec distribution. There is another open PR containing a test environment
and tests, but it is currently in progress.
Partially addresses #3

Add K8s Inject Cert endpoint to API spec

---

bin/api_test
bin/bundle_spec
bin/cli
bin/generate_client
bin/get_conjur_admin_key
bin/integration_tests
bin/lint_spec
bin/lint_tests
bin/start
bin/start_conjur
bin/stop
bin/util

Some OS' wont have `realpath` installed by default so we cannot rely on it in scripts
Updated the script not to rely on `realpath`
Resolves #136

Removed use of realpath in generate_client script

---

test/python/test_status_api.py

Adds some basic tests for using the previously non-tested authenticators on the authenticator status endpoint. We didn't want the overhead of standing up cloud authenticators so we ended up writing unit tests for the two alternates.
Resolves #99

Added extra authenticators for auth status test

---

.github/workflows/k8s_inject.yml
.gitignore
Jenkinsfile
requirements.txt
test/python/k8s/Dockerfile
test/python/k8s/deploy_test
test/python/k8s/kubernetes/conjur-cli.yml
test/python/k8s/kubernetes/test-app-conjur-authenticator-role-binding.yml
test/python/k8s/kubernetes/test-app.yml
test/python/k8s/policy/load_policies.sh
test/python/k8s/policy/templates/app-identity-def.template.yml
test/python/k8s/policy/templates/cluster-authn-svc-def.template.yml
test/python/k8s/policy/templates/project-authn-def.template.yml
test/python/k8s/setup_env
test/python/k8s/start
test/python/k8s/test_client_cert_inject.py
test/python/k8s/utils

My last PR added the `/authn-k8s/:service_id/inject_client_cert` endpoint to the OpenAPI spec.
This PR adds:
- an environment for testing this endpoint,
- test cases for each possible HTTP status response, 
- a stage in the project's Jenkins pipeline to run the tests,
- a GitHub Action to run the test daily, and when files pertaining to the endpoint are changed.
Resolves #3

Add K8s Inject Cert Endpoint

---

bin/api_test
spec/authentication.yaml

Sometimes Nginx will interfere with the raw return codes from Conjur itself so we need to run this test against bare Conjur to get all the intended return codes.
Resolves #151
Relates to cyberark/conjur#[Relevant conjur issue number]

Contract test now runs against conjur w/out nginx

---

CHANGELOG.md
spec/secrets.yml
test/python/test_secrets_api.py

Added the new Accept-Encoding header parameter to the secrets batch endpoint and added a new test for the added functionality.
Resolves #145
Relates to PR cyberark/conjur#2065

Added secrets batch encoding feature

---

CHANGELOG.md
CONTRIBUTING.md
README.md
bin/start
bin/start_spec_ui
bin/util

Updated the `start_editor` script to bundle the spec, and point at the bundled spec. Also renamed the script to `start_swagger_ui` to reflect the fact that it is not really possible to use it as an editor in this project because the spec is split over multiple files.  The documentation has been updated to reflect these changes.
Resolves #168

Update swagger ui info

---

CHANGELOG.md
spec/authentication.yml
spec/cert-auth.yml
spec/host-factory.yml
spec/openapi.yml
spec/policies.yml
spec/public-keys.yml
spec/resources.yml
spec/roles.yml
spec/secrets.yml
spec/status.yml
test/python/test_status_api.py

This header applies to all endpoints, so the parameter is placed in the path instead of on each individual endpoint. This helps reduce some duplication, unfortunately it is not possible to apply one parameter globally.
Resolves #175

Added new request header for all endpoints

---

CONTRIBUTING.md

Added a section in CONTRIBUTING for Conjur Enterprise developers detailing how the annotations work as well as how to generate/run tests against the Enterprise version of the spec. Also added notes about Enterprise releases.
Resolves #170 & #164

Updated CONTRIBUTING with Enterprise info

---

bin/api_test
spec/host-factory.yml
test/python/test_host_factory_api.py

Host Factory endpoints were only tested for successful requests.
This PR includes tests that confirm all possible status responses.
`500` responses were listed for each endpoint. These were removed.
Resolves #161

Update Host Factory tests

---

test/python/auth/test_authentication_external_api.py

Commented test case requested adding test
cases for 404 responses on external auth
endpoints. This was a remnant from when
these endpoints were generalized.
Resolves #180

Remove stale auth test

---

bin/generate_kong_config
test/python/k8s/Dockerfile

This PR fixes two small bugs in example flows.
- `test/python/k8s/Dockerfile` : a recent update to `bin/generate_client` changed the output dir of generated clients
- `bin/generate_kong_config` : an Insomnia Inso dependency breaks with recently released Node.js 16
No linked issue

Small updates for example workflows

---

CHANGELOG.md
spec/secrets.yml

This allows the java client to properly set a secret in the generated client. Currently it is unable to properly handle the `format: binary` type for strings.

Updated request body on secret creation

---

CHANGELOG.md
spec/authentication.yml
test/python/auth/test_authentication_external_api.py

Need to specify that no authentication method should be used when using some authentication methods. If nothing is specified for the field then some utilities assume all of them should be used. This causes issues.

Update security preferences

---

CONTRIBUTING.md
README.md
examples/python/README.md
examples/ruby/README.md
spec/openapi.yml
spec/status.yml

Updating naming for Conjur editions
- converts `Conjur OSS` to `Conjur Open Source`
- converts `DAP`/`Dynamic Access Provider` to `Conjur Enterprise`
- maintains `Conjur OSS Suite` and `Conjur Open Source Suite`
This is part of an automated batch of PRs across many repos listed in [cyberark/community#92](https://github.com/cyberark/community/issues/92)

Updating naming for Conjur editions

---

.github/workflows/api_contract.yml

Updated API contract test so it runs daily at midnight. This is to make sure that we see a failure before someone opens a PR which could take a while.

Updated contract test action to run daily at 12am

---

CHANGELOG.md
spec/authentication.yml

Aligns the spec with conjur following the [PR](https://github.com/cyberark/conjur/pull/2360)
[ONYX- 9758](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-9758)

Remove 502 response from oidc autrhenticator

---

spec/authentication.yml
spec/openapi.yml
test/config/policy.yaml
test/python/auth/test_authentication_external_api.py

Add new route for enabling authenticator with default service
Resolves #[ONYX-13302](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13302)
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or

Add new route for enabling authenticator with default service

---

test/config/oidc/fetchCertificate

The keycloak certs are now properly fetched based on updates to Conjur OIDC.
[related](https://github.com/cyberark/conjur-sdk-java/pull/66)
CyberArk internal issue link: [insert issue ID]()
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or

Updated how keycloak container certs are retrieved

---

CHANGELOG.md
spec/roles.yml
test/python/roles/test_roles_api.py
test/python/roles/test_roles_query_params_api.py

Fix the OpenAPI description CI build.
- Remove 403 responses, and tests confirming them, from the Roles API. See cyberark/conjur#2755.
- Update list of `admin` user system memberships.
CNJR-1816
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or

Fix Roles API test failures

---

bin/test_integration
docker-compose.yml
test/config/oidc-webservice.yml
test/config/oidc/fetchCertificate
test/python/api_config.py

Fix pipeline failures due to OpenSSL changes. 
Use updated authn-oidc configurability to provide the CA cert via Conjur policy
NOTE: this update is not required for this flow to work. The new `ca-cert` variable does not break the previous strategy. The reason these tests failed was a faulty openssl command:
```diff
- openssl x509 -hash -in /etc/ssl/certs/keycloak.pem -out /dev/null
+ openssl x509 -hash -in /etc/ssl/certs/keycloak.pem --noout
```
Additional changes:
- Fix docker compose external network deprecation warnings
NOTE: Kong examples are still failing due to changes with the Inso CLI that will be resolved in a separate effort.
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or

Use ca-cert variable for keycloak tests
