cyberark/conjur-openapi-spec

.coveragerc
.gitignore
Jenkinsfile
README.md
bin/integration_tests

Adds test coverage metrics to the Jenkins pipeline
Resolves #21

Code coverage

---

CHANGELOG.md
spec/openapi.yml
spec/status.yml
test/python/api_config.py
test/python/test_status_api.py

Added the /whoami endpoint to the openapi spec file and added integration tests for the Python client
Resolves #56

Add whoami endpoint

---

docker-compose.yml

Allows us to make sure the api spec is up to date with all the latest changes to conjur
Resolves #80

Switched to using conjur edge image for testing and development

---

CHANGELOG.md
spec/openapi.yml
spec/status.yml
test/config/webservice.yml
test/python/api_config.py
test/python/test_status_api.py

Added the authenticator status endpoint to the API spec.
Resolves #59

Add authenticator status endpoint

---

CHANGELOG.md
spec/openapi.yml
spec/resources.yml
test/config/.pylintrc
test/python/test_resources_api.py

This PR adds:
- `/resources` endpoint
- `/resources/{account}/{kind}` endpoint
- integration tests for each
Resolves #62 and #71

Update Resources API Spec

---

CHANGELOG.md
spec/openapi.yml
spec/status.yml
test/python/test_status_api.py

Added the /authenticators endpoint to the openapi spec
Resolves #58

Authenticators endpoint

---

.gitignore
CONTRIBUTING.md
bin/cli
docker-compose.yml
spec/authentication.yaml

Added a cli container to the docker-compose file and a script for starting up and attaching it.

Added .coverage file to .gitignore

---

.github/workflows/rebase.yml

Updated so we use the new version of the enforce rebase action in the cyberark org

Updated rebase action to use cyberark org

---

CHANGELOG.md
spec/openapi.yml
spec/roles.yml
test/python/test_roles_api.py

Added the `graph` query parameter to the roles endpoint
Resolves #69

Add roles graph

---

spec/openapi.yml

Ensure the description is clear it's for OSS only

---

spec/openapi.yml

Also organizes individual paths to show in the main doc in the same order
as they show in the individual docs
n/a

Ensure all tags have headers in the paths section

---

.github/workflows/linting.yml
CHANGELOG.md
bin/integration_tests
bin/lint_tests
docker-compose.yml
requirements.txt
spec/authentication.yaml
spec/openapi.yml
test/config/oidc-webservice.yml
test/config/oidc/create_client
test/config/oidc/create_user
test/config/oidc/fetchCertificate
test/config/oidc/keycloak/standalone.xml
test/config/policy.yaml
test/python/api_config.py
test/python/test_authn_api.py
test/python/test_roles_api.py
test/python/test_status_api.py

Added the authenticate endpoint for OIDC to the spec file along with integration tests.
Resolves #60

Add OIDC authenticate endpoint

---

.github/workflows/update-wiki.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
bin/generate_client
bin/integration_tests
templates/markdown/README.mustache
templates/markdown/api.mustache
templates/markdown/model.mustache

Updated generate_client bash script for user friendliness and usability and added a github action which will run nightly in order to update the Wiki with any new changes in the repository
Resolves #86

Wiki updater

---

.github/workflows/commits.yml

Added GitHub workflow to check commit subject style

Added workflow for checking commit style

---

README.md

Explain that this spec and materials generated from it can be used with Conjur EE as well as Conjur.
Resolves #112

Added Conjur EE (DAP) section to README

---

README.md

Updated the README to link to the new wiki page about reading the spec file.
Resolves #109

Updated README to link to new wiki page

---

CONTRIBUTING.md
test/README.md

Added info about testing and how the test frameworks we use actually work. Also added reference to the `bin/bundle_spec` script and what its purpose is.

Add docs to fill two small gaps

---

.github/workflows/changelog.yml
CONTRIBUTING.md
bin/parse_changelog

Added a script for verifying the changelog and a new action to run on PR's.

Added script & action for changelog verification

---

.github/workflows/generate_collection.yml
CHANGELOG.md
README.md
bin/generate_postman_collection
examples/postman/README.md
examples/postman/postman_env_setup.py

Adds scripts to generate a collection and environment
for easy importing into Postman, workflow documented
in README.
Uses the `postman/generate_collection` script in a GHA
workflow, which archives the collection as an artifact for
every PR.
Resolves #92

Adds scripts/docs for exploring API with Postman

---

CHANGELOG.md
bin/generate_client
examples/python/python_client.py
examples/ruby/ruby_client.rb
examples/ruby/start
spec/authentication.yml
spec/config/python.yml
spec/config/ruby.yml
spec/host-factory.yml
spec/openapi.yml
spec/policies.yml
spec/public-keys.yml
spec/resources.yml
spec/roles.yml
spec/secrets.yml
spec/status.yml
test/config/policy.yaml
test/config/webservice.yml
test/python/api_config.py
test/python/k8s/test_client_cert_inject.py
test/python/test_authentication_api.py
test/python/test_certificate_authority_api.py
test/python/test_host_factory_api.py
test/python/test_policies_api.py
test/python/test_public_keys_api.py
test/python/test_resources_api.py
test/python/test_roles_api.py
test/python/test_secrets_api.py
test/python/test_status_api.py
test/test-server.py

Updated the names of some operation id's based on feedback from @jonahx 
Resolves #129
Relates to cyberark/conjur#[Relevant conjur issue number]

Updated spec naming scheme

---

CHANGELOG.md
examples/python/python_client.py
examples/ruby/ruby_client.rb
spec/authentication.yml
spec/cert-auth.yml
spec/host-factory.yml
spec/openapi.yml
spec/policies.yml
spec/public-keys.yml
spec/resources.yml
spec/roles.yml
spec/secrets.yml
spec/status.yml
test/python/test_host_factory_api.py
test/python/test_resources_api.py

Updated response schemas for the endpoints and made a minor update to the way we handle multi-line strings in YAML (moved to block literal in place of quoted.
Resolves #43

Update spec response descriptions

---

.github/workflows/release.yml
.gitignore
CONTRIBUTING.md
bin/release

Added script for collecting artifacts to be attached to each release as well as a GitHub action to release the spec on push of a version tag.
Related to #111

Added utilities for releasing project

---

CHANGELOG.md
examples/ruby/ruby_client.rb
examples/ruby/start
spec/config/ruby.yml
templates/ruby/configuration.mustache
templates/ruby/gem.mustache

Added environmental variable support and helper functions for configuring authentication.
Relates to #91

Update ruby client

---

CHANGELOG.md
spec/openapi.yml
spec/secrets.yml

Add updated response code to the batch secrets endpoint.
Relates to [cyberark/conjur#2124](https://github.com/cyberark/conjur/pull/2124)

Added new response code to batch secrets request

---

bin/release

Updates script to collect new objects based on the changes
once DAP functionality was added to the project. Also changed
base filename in the normal spec archive.
Resolves #14

Update release artifact creation script

---

README.md

Update project intro in README

---

spec/resources.yml

Quick update to make sure the API spec is actually in line with the API itself

Updated resources response for accuracy

---

CHANGELOG.md

Simple changelog update to include a change that wasn't previously documented

Update changelog with JWT addition

---

bin/start_conjur
test/python/auth/test_authentication_external_api.py

Adds tests for new JWT authentication endpoint `/authn-jwt/{service_id}/{account}/authenticate`
Fixes Jenkins build instability

Add tests for JWT auth endpoint

---

spec/authentication.yml
spec/openapi.yml
test/python/auth/test_authentication_external_api.py

- Add new python test for JWT authentication with id optional parameter
ONYX-9612

ONYX-9612 Add new test for JWT authenticate with id
